# Generated by Django 5.0.4 on 2024-04-21 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('name', models.CharField(max_length=160)),
                ('email', models.CharField(default='email', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=255)),
                ('food_type', models.CharField(blank=True, choices=[('Raw', 'Raw'), ('Cooked', 'Cooked')], max_length=100, null=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='Donated_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=11)),
                ('location', models.CharField(max_length=255)),
                ('food_type', models.CharField(max_length=100)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ngo')),
            ],
        ),
    ]
