# Generated by Django 5.0.4 on 2024-04-21 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_donation_ngo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
